### PR TITLE
Fix @PlatformIO Library manifest

### PR DESCRIPTION
**Pull request by ivankravets**

### CODE REVIEW

**Review by dgomes — APPROVED** [review]
Well spotted!

**Comment by ivankravets** [comment]
Does this library do some functionality as this official http://platformio.org/lib/show/1297/IndustrialShields ?

**Comment by dgomes** [comment]
I was not aware of this official library. Either way, mine predates this one by several months :)

From what I read into the code, it's just basic examples (very complete!).

Mine focus on the relay's part, with higher level functions, but I'm willing to incorporate other stuff into mine and/or merge my stuff with the official library

**Comment by ivankravets** [comment]
Thanks! http://platformio.org/lib/show/1298/Industrial%20Shields

**Pull request merged**
